[package]
name = "generativeart"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.3"
ndarray = "0.15.6"
sdl2 = "0.35.2"

[profile.dev]
opt-level = 1
